version: "3.9"

services:
  demo-db:
    image: postgres:15.1-alpine
    container_name: Demo-DB
    restart: always
    volumes:
      - ./data/00-schema.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./data/01-data.sql:/docker-entrypoint-initdb.d/02-data.sql
      - ./data/02-update.sql:/docker-entrypoint-initdb.d/03-update.sql
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PSW}
    ports:
      - "5432:5432"